### ISSUE TITLE
Loop function doesn't work

### ISSUE THREAD

**Issue by JohnyP36** [JohnyP36/YT-Nonstop#8]
### Prerequisites

- [X] I've read the [Code of Conduct](https://github.com/JohnyP36/YT-Nonstop/blob/main/.github/CODE_OF_CONDUCT.md) and the [Contributing Guidelines](https://github.com/JohnyP36/YT-Nonstop/blob/main/.github/CONTRIBUTING.md)
- [X] I performed a [cursory search of the issue tracker](https://github.com/JohnyP36/YT-Nonstop/issues) to avoid opening a duplicate issue  *--  Your issue may already be reported.*
- [X] I am running the latest version of the extension

### I tried to reproduce the issue when...

- [X] Other webextensions related to Youtube are disabled  *-- Just to ensure there is no issues or conflicts with other webbrowser extensions.*
- [ ] using a new, unmodified browser profile

### Describe the issue

Since some weeks the function to loop your playlist doesn't work anymore.  
So, it doesn't matter if I toggle on or off the loop button in the extension popup: it has no affect on `www.youtube.com`.

### Browser & Extension version

MS Edge 94 & 1.6.4

### Notes

I looked into your .js files, and into the source code of youtube.com, but for so far I didn't found the error. 
Maybe youtube has change their code.

**Comment by BPower0036** [comment]
Maybe you should try `using a new, unmodified browser profile` or just delete that functionality, because why do you want this?

**Comment by JohnyP36** [comment]
Fixed by https://github.com/JohnyP36/YT-Nonstop/commit/5e8accb54e81772d5f349cc0d85f1cfa259cd1da & https://github.com/JohnyP36/YT-Nonstop/commit/e37357126eaf5346980f62ef54ce13c0d7b78fa9

**Comment by JohnyP36** [comment]
### Warnings

1. Drawback: you can only loop a video in a playlist if you turn "loop playlist" on.
2. The loop function for YouTube Music will only work if the language of YouTube is set to:  English, German, French or Dutch. 
  *If you want this extension to support your language, please open an issue.*
